04 - SSO/src/M183/Models/ErrorViewModel.cs
using System;

namespace M183.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04 - SSO/src/M183/Controllers/AcmController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Google.Apis.Auth;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authentication.MicrosoftAccount;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace M183.Controllers
{
    public class AcmController : Controller
    {
        private readonly ILogger<AcmController> _logger;


        public AcmController(ILogger<AcmController> logger)
        {
            this._logger        = logger;
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult LoginWithGoogle()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = Url.Action("Account")},
                GoogleDefaults.AuthenticationScheme);
        }

        [HttpGet]
        public IActionResult LoginWithMicrosoft()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = Url.Action("Account") },
                MicrosoftAccountDefaults.AuthenticationScheme);
        }

        [HttpGet]
        public IActionResult Account()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            return Unauthorized();
        }

        [HttpGet]
        public IActionResult LoginWithGithub()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = Url.Action("Account")},
                GoogleDefaults.AuthenticationScheme);
        }

        [HttpGet]
        public async ValueTask<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("ExternalLogin");
            return RedirectToAction("Index", "Home");
        }


    }
}

04 - SSO/src/M183/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using M183.Models;

namespace M183.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

04 - SSO/src/M183/Views/Acm/Account.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Account";
    ClaimsIdentity user = ((ClaimsIdentity)User.Identity);

}
<h2>@ViewData["Title"]</h2>

<div class="text-center">
    @if (User.Identity.IsAuthenticated)
    {
        <h2>Sie sind als @user.Name über @User.Identity.AuthenticationType angemeldet.</h2>

        <div class="text-center">
            @if (User.Identity.AuthenticationType == "Google")
            {
                <img src="@user.Claims.FirstOrDefault(e => e.Type == "urn:google:picture")?.Value)" style="border-radius: 50%; max-height: 50px;">
            }
        </div>

        <div>
            <b>Provider: </b>
            <span>@user.AuthenticationType
        </div>

        <div>
            <b>Name:</b>
            <span>@user.Name</span>
        </div>
        
        <div>
            <b>EMail:</b>
            <span>@user.Claims.FirstOrDefault(e => e.Type == ClaimTypes.Email).Value</span>
        </div>

        <a href="@Url.Action("Logout", "Acm")" class="btn btn-primary">Logout</a>
    }
</div>

04 - SSO/src/M183/Views/Acm/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
<h2>@ViewData["Title"]</h2>

<h2>Sie sind gerade nicht angemeldet</h2>
<a href="@Url.Action("LoginWithGoogle", "Acm")" class="btn btn-danger"><i class="fab fa-google"></i>   Mit Google anmelden.</a>
<a href="@Url.Action("LoginWithMicrosoft", "Acm")" class="btn btn-primary"><i class="fab fa-microsoft"></i>   Mit Microsoft anmelden.</a>

04 - SSO/src/M183/Views/Home/Index.cshtml
@using System.Security.Claims
@{
    ViewData["Title"] = "Home Page";
    ClaimsIdentity user = ((ClaimsIdentity)User.Identity);
}

<div class="text-center">
    @if (User.Identity.IsAuthenticated)
    {
        <h2>Sie sind als @user.Name über @User.Identity.AuthenticationType angemeldet.</h2>

        <div class="text-center">
            @if (User.Identity.AuthenticationType == "Google")
            {
                <img src="@user.Claims.FirstOrDefault(e => e.Type == "urn:google:picture")?.Value)" style="border-radius: 50%; max-height: 50px;">
            }
        </div>

        <div>
            <b>Provider: </b>
            <span>@user.AuthenticationType
        </div>

        <div>
            <b>Name:</b>
            <span>@user.Name</span>
        </div>
        
        <div>
            <b>EMail:</b>
            <span>@user.Claims.FirstOrDefault(e => e.Type == ClaimTypes.Email).Value</span>
        </div>

        <a href="@Url.Action("Logout", "Acm")" class="btn btn-primary">Logout</a>
    }
    else
    {
        <h2>Sie sind gerade nicht angemeldet</h2>

        <a href="@Url.Action("LoginWithGoogle", "Acm")" class="btn btn-danger"><i class="fab fa-google"></i>   Mit Google anmelden.</a>
        <a href="@Url.Action("LoginWithMicrosoft", "Acm")" class="btn btn-primary"><i class="fab fa-microsoft"></i>   Mit Microsoft anmelden.</a>
    }
</div>

04 - SSO/src/M183/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - M183</title>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">M183</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - M183</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>